# -*- coding: utf-8 -*-
"""Auto-generated by tools/generate.py -- DO NOT EDIT."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List

__version__ = "1.0.3"
__commit__ = "8e9c1a0"
__snapshot__ = False


@dataclass(frozen=True)
class PublicError:
    key: str
    status_code: int
    error_code: str
    error_msg: str
    anthropic_error_code: str

    def format_msg(self, substitutions: Dict[str, str] = None) -> str:
        msg = self.error_msg
        if substitutions:
            for k, v in substitutions.items():
                msg = msg.replace("{" + k + "}", v)
        return msg


@dataclass(frozen=True)
class InternalErrorDef:
    name: str
    external: PublicError
    message: str
    allow_retry: bool = False
    vars: List[str] = field(default_factory=list)
    cause: str = ""
    solution: str = ""

    def format_message(self, substitutions: Dict[str, str] = None) -> str:
        msg = self.message
        if substitutions:
            for k, v in substitutions.items():
                msg = msg.replace("{" + k + "}", v)
        return msg


# -- Public Errors --------------------------------------------------

INVALID_REQUEST = PublicError(
    key="invalid_request",
    status_code=400,
    error_code="BadRequestError",
    error_msg=(
        "The request is invalid. Please check the request and try " "again."
    ),
    anthropic_error_code="invalid_request_error",
)

MISSING_PARAMETER = PublicError(
    key="missing_parameter",
    status_code=400,
    error_code="BadRequestError",
    error_msg="Missing required parameter: {parameter}.",
    anthropic_error_code="invalid_request_error",
)

CONTENT_POLICY_VIOLATION = PublicError(
    key="content_policy_violation",
    status_code=400,
    error_code="BadRequestError",
    error_msg="The request was rejected by content policy.",
    anthropic_error_code="invalid_request_error",
)

INVALID_URL = PublicError(
    key="invalid_url",
    status_code=400,
    error_code="BadRequestError",
    error_msg="The provided URL is invalid or cannot be accessed.",
    anthropic_error_code="invalid_request_error",
)

INVALID_FILE = PublicError(
    key="invalid_file",
    status_code=400,
    error_code="BadRequestError",
    error_msg="The provided file is invalid.",
    anthropic_error_code="invalid_request_error",
)

AUTH_FAILED = PublicError(
    key="auth_failed",
    status_code=401,
    error_code="AuthenticationError",
    error_msg=(
        "Authentication failed. Please provide valid "
        "authentication credentials."
    ),
    anthropic_error_code="authentication_error",
)

INVALID_API_KEY = PublicError(
    key="invalid_api_key",
    status_code=401,
    error_code="AuthenticationError",
    error_msg="Incorrect API key provided.",
    anthropic_error_code="authentication_error",
)

PERMISSION_DENIED = PublicError(
    key="permission_denied",
    status_code=403,
    error_code="PermissionDeniedError",
    error_msg="You do not have permission to access this resource.",
    anthropic_error_code="permission_error",
)

RESOURCE_NOT_FOUND = PublicError(
    key="resource_not_found",
    status_code=404,
    error_code="NotFoundError",
    error_msg="The requested resource was not found: {resource}.",
    anthropic_error_code="not_found_error",
)

REQUEST_TOO_LARGE = PublicError(
    key="request_too_large",
    status_code=413,
    error_code="RequestTooLargeError",
    error_msg="The request exceeds the maximum allowed size of {limit}.",
    anthropic_error_code="request_too_large",
)

RATE_LIMIT_EXCEEDED = PublicError(
    key="rate_limit_exceeded",
    status_code=429,
    error_code="RateLimitError",
    error_msg="Rate limit exceeded. Please slow down your requests.",
    anthropic_error_code="rate_limit_error",
)

CONCURRENCY_LIMIT_EXCEEDED = PublicError(
    key="concurrency_limit_exceeded",
    status_code=429,
    error_code="RateLimitError",
    error_msg=(
        "Too many concurrent requests. Please reduce concurrency "
        "and try again."
    ),
    anthropic_error_code="rate_limit_error",
)

INSUFFICIENT_QUOTA = PublicError(
    key="insufficient_quota",
    status_code=429,
    error_code="RateLimitError",
    error_msg=(
        "You exceeded your current quota. Please check your plan "
        "and billing details."
    ),
    anthropic_error_code="billing_error",
)

INTERNAL_ERROR = PublicError(
    key="internal_error",
    status_code=500,
    error_code="InternalServerError",
    error_msg=(
        "The server encountered an internal error. Please try again " "later."
    ),
    anthropic_error_code="api_error",
)

SERVICE_UNAVAILABLE = PublicError(
    key="service_unavailable",
    status_code=503,
    error_code="ServiceUnavailableError",
    error_msg=(
        "The service is temporarily unavailable. Please try again " "later."
    ),
    anthropic_error_code="overloaded_error",
)

REQUEST_TIMEOUT = PublicError(
    key="request_timeout",
    status_code=504,
    error_code="GatewayTimeoutError",
    error_msg="The request timed out. Please try again later.",
    anthropic_error_code="timeout_error",
)


# -- Internal Errors -------------------------------------------------

SDK_INVALID_API_KEY = InternalErrorDef(
    name="sdk.InvalidApiKey",
    external=AUTH_FAILED,
    message="Invalid API key configuration for client.",
    allow_retry=False,
    vars=[],
    cause="",
    solution=(
        "Set the DASHSCOPE_API_KEY environment variable or pass a "
        "valid api_key to AgenticRL(). You can obtain an API key "
        "through the DashScope console."
    ),
)

SDK_AGENTIC_RL_FUNCTION_REGISTRATION_FAILED = InternalErrorDef(
    name="sdk.agentic_rl.FunctionRegistrationFailed",
    external=INTERNAL_ERROR,
    message="Function component registration failed: [{inner_code}].",
    allow_retry=True,
    vars=["inner_code"],
    cause="",
    solution=(
        "Check the inner error code for details. Ensure the function code "
        "package is valid and the deployment service is reachable. Retry the "
        "register_functions() call."
    ),
)

SDK_AGENTIC_RL_DATASETS_UPLOAD_FAILED = InternalErrorDef(
    name="sdk.agentic_rl.DatasetsUploadFailed",
    external=INTERNAL_ERROR,
    message="Datasets upload failed: [{inner_code}].",
    allow_retry=True,
    vars=["inner_code"],
    cause="",
    solution=(
        "Verify your dataset files exist and are readable. Check OSS "
        "credentials and network connectivity. Retry the upload_datasets() "
        "call."
    ),
)

SDK_AGENTIC_RL_DUPLICATE_FUNCTION_NAMES = InternalErrorDef(
    name="sdk.agentic_rl.DuplicateFunctionNames",
    external=INVALID_REQUEST,
    message="Duplicate function names detected: {names}.",
    allow_retry=False,
    vars=["names"],
    cause="",
    solution=(
        "Each registered function must have a unique name. Review your "
        "RolloutFunctionComponent and RewardFunctionComponent definitions and "
        "remove any duplicate names before calling submit_job()."
    ),
)

SDK_AGENTIC_RL_JOB_SUBMISSION_FAILED = InternalErrorDef(
    name="sdk.agentic_rl.JobSubmissionFailed",
    external=INTERNAL_ERROR,
    message="Job submission failed: [{inner_code}].",
    allow_retry=True,
    vars=["inner_code"],
    cause="",
    solution=(
        "Check the inner error code for details. Ensure the model name is "
        "valid and your account has sufficient quota. Retry submit_job() "
        "after fixing the underlying issue."
    ),
)

SDK_AGENTIC_RL_WORKFLOW_FAILED = InternalErrorDef(
    name="sdk.agentic_rl.WorkflowFailed",
    external=INTERNAL_ERROR,
    message="RL tuning workflow failed: [{inner_code}].",
    allow_retry=True,
    vars=["inner_code"],
    cause="",
    solution=(
        "This error wraps a failure in the run() workflow. Inspect the inner "
        "error code to identify which step failed (registration, upload, or "
        "submission), fix that issue, and retry run()."
    ),
)

SDK_AGENTIC_RL_UNSUPPORTED_FUNCTION_TYPE = InternalErrorDef(
    name="sdk.agentic_rl.UnsupportedFunctionType",
    external=INVALID_REQUEST,
    message="Unsupported function type: {functype}.",
    allow_retry=False,
    vars=["functype"],
    cause="",
    solution=(
        "Only ROLLOUT, REWARD, and GROUP_REWARD function types are supported. "
        "Pass a valid FunctionType enum value to test_functions()."
    ),
)

SDK_AGENTIC_RL_FUNCTION_TEST_FAILED = InternalErrorDef(
    name="sdk.agentic_rl.FunctionTestFailed",
    external=INTERNAL_ERROR,
    message="Function test failed: [{inner_code}].",
    allow_retry=True,
    vars=["inner_code"],
    cause="",
    solution=(
        "Check the inner error code and the function logs for details. Verify "
        "that the function code runs correctly with the provided input_data. "
        "Fix the function and retry test_functions()."
    ),
)

SDK_AGENTIC_RL_FUNCTION_TEST_TIMEOUT = InternalErrorDef(
    name="sdk.agentic_rl.FunctionTestTimeout",
    external=REQUEST_TIMEOUT,
    message="Function test timed out after {timeout} seconds.",
    allow_retry=True,
    vars=["timeout"],
    cause="",
    solution=(
        "The function did not return within the timeout period. Profile your "
        "function for slow operations (e.g. large model inference, network "
        "calls) and optimize it. Consider increasing the timeout if the "
        "function legitimately takes longer."
    ),
)


SDK_AGENTIC_RL_INPUT_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.InputError",
    external=INVALID_REQUEST,
    message="Invalid input data detected during validation.",
    allow_retry=False,
    vars=[],
    cause="",
    solution=(
        "Check the input data passed to the function. Ensure all required "
        "fields are present and have valid types. Refer to the RolloutInput / "
        "RewardInput / GroupRewardInput schema documentation."
    ),
)

SDK_AGENTIC_RL_OUTPUT_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.OutputError",
    external=INTERNAL_ERROR,
    message="Service response failed output validation checks.",
    allow_retry=False,
    vars=[],
    cause="",
    solution=(
        "The function output did not pass validation. Ensure your function "
        "returns a valid RolloutOutput / RewardOutput / GroupRewardOutput "
        "object with all required fields populated."
    ),
)

SDK_AGENTIC_RL_BASE_CONNECTION_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.BaseConnectionError",
    external=INTERNAL_ERROR,
    message="Connection-related error occurred.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Check your network connectivity and ensure the target service "
        "endpoint is reachable. Verify firewall rules and proxy settings."
    ),
)

SDK_AGENTIC_RL_OSS_CONNECTION_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.OSSConnectionError",
    external=INTERNAL_ERROR,
    message="Connecting to OSS storage service failed.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Verify that the OSS endpoint URL is correct and the OSS service is "
        "accessible. Check your API key permissions for OSS access. Ensure "
        "you are in a region that supports OSS connectivity."
    ),
)

SDK_AGENTIC_RL_OSS_UPLOAD_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.OSSUploadError",
    external=INTERNAL_ERROR,
    message="File upload operation to OSS failed.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Check that the file exists, is readable, and does not exceed the "
        "upload size limit. Verify your OSS bucket permissions allow write "
        "operations."
    ),
)

SDK_AGENTIC_RL_DEPLOYMENT_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.DeploymentError",
    external=INTERNAL_ERROR,
    message="Deployment-related error occurred.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Check the deployment service status and logs. Ensure the function "
        "code package and dependencies are valid. Retry after the deployment "
        "service recovers."
    ),
)

SDK_AGENTIC_RL_REGISTRATION_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.RegistrationError",
    external=INTERNAL_ERROR,
    message="Function registration failed in the deployment system.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "The function could not be registered in the deployment system. "
        "Verify the function name is unique and the code package is valid. "
        "Check the inner error for deployment-specific details."
    ),
)

SDK_AGENTIC_RL_FUNCTION_LOAD_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.FunctionLoadError",
    external=INTERNAL_ERROR,
    message="Loading a registered function into runtime failed.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "The function could not be loaded into the runtime after "
        "registration. Check the error logs for import errors or missing "
        "dependencies in the function layer."
    ),
)

SDK_AGENTIC_RL_INSTANCE_WARMUP_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.InstanceWarmupError",
    external=INTERNAL_ERROR,
    message="Function instance health check failed after deployment.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "The function instance health check failed after deployment. Check "
        "the instance logs for startup errors. Ensure the function "
        "initializes correctly and the health endpoint responds within the "
        "timeout."
    ),
)

SDK_AGENTIC_RL_INSTANCE_QUERY_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.InstanceQueryError",
    external=INTERNAL_ERROR,
    message="Querying function instance status failed.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Could not query the function instance status. The instance may not "
        "be ready yet. Wait and retry, or check the deployment logs for "
        "errors."
    ),
)

SDK_AGENTIC_RL_FUNCTION_LAYER_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.FunctionLayerError",
    external=INTERNAL_ERROR,
    message="Creating a layer of function failed.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Failed to create the function dependency layer. Check that the "
        "requirements.txt or setup.py is valid and all dependencies are "
        "installable. Review the layer build logs for details."
    ),
)

SDK_AGENTIC_RL_DATASETS_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.DatasetsError",
    external=INTERNAL_ERROR,
    message="Update datasets failed in the deployment system.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Failed to update datasets in the deployment system. Verify the "
        "dataset IDs are valid and the dataset files are accessible. Retry "
        "after fixing the underlying issue."
    ),
)

SDK_AGENTIC_RL_VALIDATION_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.ValidationError",
    external=INVALID_REQUEST,
    message="Data validation failed.",
    allow_retry=False,
    vars=[],
    cause="",
    solution=(
        "One or more data fields failed validation. Check the error message "
        "for the specific field and fix the value according to the schema "
        "documentation."
    ),
)

SDK_AGENTIC_RL_CONFIGURATION_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.ConfigurationError",
    external=INVALID_REQUEST,
    message="Invalid system configuration detected.",
    allow_retry=False,
    vars=[],
    cause="",
    solution=(
        "Check your YAML configuration file or initialization parameters. "
        "Ensure all required fields (model, functions, datasets) are "
        "correctly specified. Refer to the AgenticRL configuration "
        "documentation."
    ),
)

SDK_AGENTIC_RL_BASE_PERMISSION_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.BasePermissionError",
    external=PERMISSION_DENIED,
    message="Operation lacks required permissions.",
    allow_retry=False,
    vars=[],
    cause="",
    solution=(
        "Your API key does not have the required permissions. Ensure your "
        "account has access to AgenticRL, OSS, and Function Compute services. "
        "Contact your administrator to grant the necessary permissions."
    ),
)

SDK_AGENTIC_RL_IO_ERROR_WITH_CODE = InternalErrorDef(
    name="sdk.agentic_rl.IOErrorWithCode",
    external=INTERNAL_ERROR,
    message="General I/O operation failure.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "A file or network I/O operation failed. Check file paths, "
        "permissions, and network connectivity. Review the error message for "
        "the specific operation that failed."
    ),
)


SDK_AGENTIC_RL_ERROR = InternalErrorDef(
    name="sdk.agentic_rl.Error",
    external=INTERNAL_ERROR,
    message="Base client error occurred.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "An unexpected AgenticRL error occurred. Check the error "
        "message and logs for details. If the issue persists, "
        "submit a bug report to the DashScope SDK team."
    ),
)

SDK_AGENTIC_RL_RUNTIME_ERROR_WITH_CODE = InternalErrorDef(
    name="sdk.agentic_rl.RuntimeErrorWithCode",
    external=INTERNAL_ERROR,
    message="Runtime error occurred in client.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "An unexpected runtime error occurred. Check the error "
        "message and traceback for details. If the issue persists, "
        "submit a bug report to the DashScope SDK team."
    ),
)

SDK_AGENTIC_RL_VALUE_ERROR_WITH_CODE = InternalErrorDef(
    name="sdk.agentic_rl.ValueErrorWithCode",
    external=INVALID_REQUEST,
    message="Invalid value encountered in client.",
    allow_retry=False,
    vars=[],
    cause="",
    solution=(
        "An invalid value was encountered. Check the function parameters and "
        "input data. Ensure all values conform to the expected types and "
        "ranges."
    ),
)

SDK_AGENTSTUDIO_API_CONNECTION_ERROR = InternalErrorDef(
    name="sdk.agentstudio.APIConnectionError",
    external=INTERNAL_ERROR,
    message="Failed to connect to the AgentStudio service.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Check your network connectivity and ensure the AgentStudio endpoint "
        "(base_url / region) is reachable. Verify firewall and proxy "
        "settings."
    ),
)

SDK_AGENTSTUDIO_API_TIMEOUT_ERROR = InternalErrorDef(
    name="sdk.agentstudio.APITimeoutError",
    external=REQUEST_TIMEOUT,
    message="The request to the AgentStudio service timed out.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "The request did not complete within the timeout period. Increase the "
        "client timeout or retry the request."
    ),
)

SDK_AGENTSTUDIO_STREAM_ERROR = InternalErrorDef(
    name="sdk.agentstudio.StreamError",
    external=INTERNAL_ERROR,
    message="The SSE stream encountered a fatal protocol error.",
    allow_retry=True,
    vars=[],
    cause="",
    solution=(
        "Retry the streaming request. If the error persists, "
        "report it to the DashScope SDK team."
    ),
)

SDK_AGENTSTUDIO_STREAM_CLOSED_ERROR = InternalErrorDef(
    name="sdk.agentstudio.StreamClosedError",
    external=INVALID_REQUEST,
    message="Attempted I/O on an already-closed stream.",
    allow_retry=False,
    vars=[],
    cause="",
    solution=(
        "Do not read from a stream after it has been closed. Consume the "
        "stream within its context manager or before calling close()."
    ),
)


# -- Catalogs ------------------------------------------------------
PUBLIC_ERRORS = [
    INVALID_REQUEST,
    MISSING_PARAMETER,
    CONTENT_POLICY_VIOLATION,
    INVALID_URL,
    INVALID_FILE,
    AUTH_FAILED,
    INVALID_API_KEY,
    PERMISSION_DENIED,
    RESOURCE_NOT_FOUND,
    REQUEST_TOO_LARGE,
    RATE_LIMIT_EXCEEDED,
    CONCURRENCY_LIMIT_EXCEEDED,
    INSUFFICIENT_QUOTA,
    INTERNAL_ERROR,
    SERVICE_UNAVAILABLE,
    REQUEST_TIMEOUT,
]
INTERNAL_ERRORS = [
    SDK_INVALID_API_KEY,
    SDK_AGENTIC_RL_FUNCTION_REGISTRATION_FAILED,
    SDK_AGENTIC_RL_DATASETS_UPLOAD_FAILED,
    SDK_AGENTIC_RL_DUPLICATE_FUNCTION_NAMES,
    SDK_AGENTIC_RL_JOB_SUBMISSION_FAILED,
    SDK_AGENTIC_RL_WORKFLOW_FAILED,
    SDK_AGENTIC_RL_UNSUPPORTED_FUNCTION_TYPE,
    SDK_AGENTIC_RL_FUNCTION_TEST_FAILED,
    SDK_AGENTIC_RL_FUNCTION_TEST_TIMEOUT,
    SDK_AGENTIC_RL_INPUT_ERROR,
    SDK_AGENTIC_RL_OUTPUT_ERROR,
    SDK_AGENTIC_RL_BASE_CONNECTION_ERROR,
    SDK_AGENTIC_RL_OSS_CONNECTION_ERROR,
    SDK_AGENTIC_RL_OSS_UPLOAD_ERROR,
    SDK_AGENTIC_RL_DEPLOYMENT_ERROR,
    SDK_AGENTIC_RL_REGISTRATION_ERROR,
    SDK_AGENTIC_RL_FUNCTION_LOAD_ERROR,
    SDK_AGENTIC_RL_INSTANCE_WARMUP_ERROR,
    SDK_AGENTIC_RL_INSTANCE_QUERY_ERROR,
    SDK_AGENTIC_RL_FUNCTION_LAYER_ERROR,
    SDK_AGENTIC_RL_DATASETS_ERROR,
    SDK_AGENTIC_RL_VALIDATION_ERROR,
    SDK_AGENTIC_RL_CONFIGURATION_ERROR,
    SDK_AGENTIC_RL_BASE_PERMISSION_ERROR,
    SDK_AGENTIC_RL_IO_ERROR_WITH_CODE,
    SDK_AGENTIC_RL_ERROR,
    SDK_AGENTIC_RL_RUNTIME_ERROR_WITH_CODE,
    SDK_AGENTIC_RL_VALUE_ERROR_WITH_CODE,
    SDK_AGENTSTUDIO_API_CONNECTION_ERROR,
    SDK_AGENTSTUDIO_API_TIMEOUT_ERROR,
    SDK_AGENTSTUDIO_STREAM_ERROR,
    SDK_AGENTSTUDIO_STREAM_CLOSED_ERROR,
]
