# -*- coding: utf-8 -*-
"""Auto-generated by tools/generate.py -- DO NOT EDIT."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List


@dataclass(frozen=True)
class PublicError:
    key: str
    status_code: int
    error_code: str
    error_msg: str
    anthropic_error_code: str

    def format_msg(self, variables: Dict[str, str] = None) -> str:
        msg = self.error_msg
        if variables:
            for k, v in variables.items():
                msg = msg.replace("{" + k + "}", v)
        return msg


@dataclass(frozen=True)
class InternalErrorDef:
    name: str
    external: PublicError
    message: str
    allow_retry: bool = False
    vars: List[str] = field(default_factory=list)
    cause: str = ""
    solution: str = ""

    def format_message(self, variables: Dict[str, str] = None) -> str:
        msg = self.message
        if variables:
            for k, v in variables.items():
                msg = msg.replace("{" + k + "}", v)
        return msg


# -- Public Errors --------------------------------------------------

INVALID_REQUEST = PublicError(
    key="invalid_request",
    status_code=400,
    error_code="BadRequestError",
    error_msg=(
        "The request is invalid. Please check the request and try " "again."
    ),
    anthropic_error_code="invalid_request_error",
)

MISSING_PARAMETER = PublicError(
    key="missing_parameter",
    status_code=400,
    error_code="BadRequestError",
    error_msg="Missing required parameter: {parameter}.",
    anthropic_error_code="invalid_request_error",
)

CONTENT_POLICY_VIOLATION = PublicError(
    key="content_policy_violation",
    status_code=400,
    error_code="BadRequestError",
    error_msg="The request was rejected by content policy.",
    anthropic_error_code="invalid_request_error",
)

INVALID_URL = PublicError(
    key="invalid_url",
    status_code=400,
    error_code="BadRequestError",
    error_msg="The provided URL is invalid or cannot be accessed.",
    anthropic_error_code="invalid_request_error",
)

INVALID_FILE = PublicError(
    key="invalid_file",
    status_code=400,
    error_code="BadRequestError",
    error_msg="The provided file is invalid.",
    anthropic_error_code="invalid_request_error",
)

AUTH_FAILED = PublicError(
    key="auth_failed",
    status_code=401,
    error_code="AuthenticationError",
    error_msg=(
        "Authentication failed. Please provide valid "
        "authentication credentials."
    ),
    anthropic_error_code="authentication_error",
)

INVALID_API_KEY = PublicError(
    key="invalid_api_key",
    status_code=401,
    error_code="AuthenticationError",
    error_msg="Incorrect API key provided.",
    anthropic_error_code="authentication_error",
)

PERMISSION_DENIED = PublicError(
    key="permission_denied",
    status_code=403,
    error_code="PermissionDeniedError",
    error_msg="You do not have permission to access this resource.",
    anthropic_error_code="permission_error",
)

RESOURCE_NOT_FOUND = PublicError(
    key="resource_not_found",
    status_code=404,
    error_code="NotFoundError",
    error_msg="The requested resource was not found: {resource}.",
    anthropic_error_code="not_found_error",
)

REQUEST_TOO_LARGE = PublicError(
    key="request_too_large",
    status_code=413,
    error_code="RequestTooLargeError",
    error_msg="The request exceeds the maximum allowed size of {limit}.",
    anthropic_error_code="request_too_large",
)

RATE_LIMIT_EXCEEDED = PublicError(
    key="rate_limit_exceeded",
    status_code=429,
    error_code="RateLimitError",
    error_msg="Rate limit exceeded. Please slow down your requests.",
    anthropic_error_code="rate_limit_error",
)

CONCURRENCY_LIMIT_EXCEEDED = PublicError(
    key="concurrency_limit_exceeded",
    status_code=429,
    error_code="RateLimitError",
    error_msg=(
        "Too many concurrent requests. Please reduce concurrency "
        "and try again."
    ),
    anthropic_error_code="rate_limit_error",
)

INSUFFICIENT_QUOTA = PublicError(
    key="insufficient_quota",
    status_code=429,
    error_code="RateLimitError",
    error_msg=(
        "You exceeded your current quota. Please check your plan "
        "and billing details."
    ),
    anthropic_error_code="billing_error",
)

INTERNAL_ERROR = PublicError(
    key="internal_error",
    status_code=500,
    error_code="InternalServerError",
    error_msg=(
        "The server encountered an internal error. Please try again " "later."
    ),
    anthropic_error_code="api_error",
)

SERVICE_UNAVAILABLE = PublicError(
    key="service_unavailable",
    status_code=503,
    error_code="ServiceUnavailableError",
    error_msg=(
        "The service is temporarily unavailable. Please try again " "later."
    ),
    anthropic_error_code="overloaded_error",
)

REQUEST_TIMEOUT = PublicError(
    key="request_timeout",
    status_code=504,
    error_code="GatewayTimeoutError",
    error_msg="The request timed out. Please try again later.",
    anthropic_error_code="timeout_error",
)
