# -*- coding: utf-8 -*-
"""Registry placeholder integrity and P1-7 regressions.

``error_registry.py`` is generated by an external tool and must not be edited,
so the guarantees consumers depend on are asserted here instead. The central
risk is a call site rendering a template without supplying its ``vars``, which
leaks a literal ``{inner_code}`` into a user-visible message.
"""
import re

import pytest

from dashscope.common.error_registry import (
    INTERNAL_ERRORS,
    PUBLIC_ERRORS,
)
from dashscope.finetune.reinforcement.common.errors import (
    AgenticRLError,
    RuntimeErrorWithCode,
    ValueErrorWithCode,
)

_PLACEHOLDER = re.compile(r"\{(\w+)\}")

_EXCEPTION_CLASSES = [AgenticRLError, RuntimeErrorWithCode, ValueErrorWithCode]


class TestRegistryIntegrity:
    def test_internal_error_names_are_unique(self):
        names = [d.name for d in INTERNAL_ERRORS]
        assert len(names) == len(set(names))

    def test_public_error_keys_are_unique(self):
        keys = [d.key for d in PUBLIC_ERRORS]
        assert len(keys) == len(set(keys))

    @pytest.mark.parametrize("err_def", INTERNAL_ERRORS, ids=lambda d: d.name)
    def test_declared_vars_match_message_placeholders(self, err_def):
        assert set(err_def.vars) == set(_PLACEHOLDER.findall(err_def.message))

    @pytest.mark.parametrize("err_def", INTERNAL_ERRORS, ids=lambda d: d.name)
    def test_unfilled_template_keeps_its_placeholder(self, err_def):
        """Locks the assumption the consumer-side guard relies on: rendering a
        templated definition with no arguments leaves ``{var}`` in place."""
        rendered = err_def.format_message()
        for var in err_def.vars:
            assert "{" + var + "}" in rendered
        if not err_def.vars:
            assert "{" not in rendered

    @pytest.mark.parametrize("err_def", INTERNAL_ERRORS, ids=lambda d: d.name)
    def test_fully_filled_template_has_no_placeholder(self, err_def):
        filled = {var: "VALUE" for var in err_def.vars}
        assert "{" not in err_def.format_message(filled)

    @pytest.mark.parametrize("err_def", INTERNAL_ERRORS, ids=lambda d: d.name)
    def test_solution_is_not_empty(self, err_def):
        assert err_def.solution.strip()

    def test_templated_public_errors_render_clean(self):
        substitutions = {
            "missing_parameter": {"parameter": "model"},
            "resource_not_found": {"resource": "qwen-plus"},
            "request_too_large": {"limit": "10MB"},
        }
        for err_def in PUBLIC_ERRORS:
            expected = substitutions.get(err_def.key)
            if expected is None:
                continue
            assert "{" not in err_def.format_msg(expected)


class TestExceptionStrNeverLeaksPlaceholders:
    @pytest.mark.parametrize("exc_cls", _EXCEPTION_CLASSES)
    @pytest.mark.parametrize("err_def", INTERNAL_ERRORS, ids=lambda d: d.name)
    def test_str_has_no_unfilled_placeholder(self, exc_cls, err_def):
        exc = exc_cls("job rejected", error_code=err_def.name)
        assert "{" not in str(exc)

    def test_templated_code_falls_back_to_own_message(self):
        exc = AgenticRLError(
            "job rejected",
            error_code="sdk.agentic_rl.WorkflowFailed",
        )
        assert str(exc) == "job rejected"

    def test_vars_free_code_still_uses_registry_message(self):
        exc = AgenticRLError(
            "job rejected",
            error_code="sdk.agentic_rl.OutputError",
        )
        assert str(exc).startswith("Service response failed output")
        assert "job rejected" in str(exc)

    def test_unknown_code_falls_back_to_own_message(self):
        exc = AgenticRLError("job rejected", error_code="sdk.not_a_real_code")
        assert str(exc) == "job rejected"
